export const corporate = [
  "_id",
  "PropertyFor",
  "Property",
  "Ptype",
  "Company Name",
  "Refrance Name",
  "Designation",
  "Email",
  "State",
  "District",
  "City",
  "Location",
  "Floor",
  "Facing",
  "Super Area",
  "Carpet Area",
  "Approx Area",
  "Budget",
  "Car Parking",
  "Water 24hr",
  "Police Station",
  "Railway Station",
  "Metro Station",
  "Hospital",

  "Image",
  "Date",
  "MarkAsRead",
  "Publish",
  "ShowAtHome"
];
export const commercial = [
  "_id",
  "PropertyFor",
  "Property",
  "Ptype",
  "Name",
  "Email",
  "State",
  "District",
  "City",
  "Location",
  "Floor",
  "Facing",
  "Super Area",
  "Carpet Area",
  "Approx Area",
  "Budget",
  "Car Parking",
  "Water 24hr",
  "Police Station",
  "Railway Station",
  "Metro Station",
  "Hospital",

  "Image",
  "Date",
  "MarkAsRead",
  "Publish",
  "ShowAtHome"
];
export const residential = [
  "_id",
  "PropertyFor",
  "Property",
  "Ptype",
  "Name",
  "State",
  "District",
  "City",
  "Location",
  "Having",
  "Floor",
  "Badrooms",
  "Bathrooms",
  "Balcony",
  "Furnish Type",
  "Facing",
  "Super Area",
  "Carpet Area",
  "Approx Area",
  "Budget",
  "Sky View",
  "Pool View",
  "Garden View",
  "Parking View",
  "Club House View",
  "Main intrance Gate View",
  "Outer Building View",
  "Swiming Pool",
  "Club House",
  "Indoor Sports",
  "Outdoor Sports",
  "Garden",
  "Car Parking",
  "Temple",
  "Police Station",
  "Railway Station",
  "Metro Station",
  "Hospital",

  "Image",
  "Date",
  "MarkAsRead",
  "Publish",
  "ShowAtHome"
];
export const pg = [
  "_id",
  "PropertyFor",
  "Property",
  "No of Rooms",
  "PG Name",
  "Refrance Person",
  "Email",
  "State",
  "District",
  "City",
  "Location",
  "Single Sharing Rooms",
  "Double Sharing Rooms",
  "Triple Sharing Rooms",
  "Four Sharing Rooms",
  "Room Size",
  "Budget Only Rooms",
  "Budget With All Meal",
  "Gim",
  "Pool",
  "Sports",
  "Parking",
  "Study Table",
  "Alram",
  "Locker",
  "Kitchen",
  "Police Station",
  "Railway Station",
  "Metro Station",
  "Hospital",

  "Image",
  "Date",
  "MarkAsRead",
  "Publish",
  "ShowAtHome"
];
export const hotel = [
  "_id",
  "PropertyFor",
  "Property",
  "No of Rooms",
  "Hotel Name",
  "Refrance Person",
  "Designation",
  "Email",
  "State",
  "District",
  "City",
  "Location",
  "Hotel Type",
  "Budget",
  "Gim",
  "Pool",
  "Bar",
  "Banquet Hall",
  "Kitchen",
  "Parking",
  "Police Station",
  "Railway Station",
  "Metro Station",
  "Hospital",

  "Image",
  "Date",
  "MarkAsRead",
  "Publish",
  "ShowAtHome"
];
export const restaurant = [
  "_id",
  "PropertyFor",
  "Property",
  "Restaurant Name",
  "Refrance Person",
  "Designation",
  "Email",
  "State",
  "District",
  "City",
  "Location",
  "Restaurant Type",
  "Seatry",
  "Budget",
  "Gim",
  "Pool",
  "Bar",
  "Banquet Hall",
  "Kitchen",
  "Parking",
  "Police Station",
  "Railway Station",
  "Metro Station",
  "Hospital",

  "Image",
  "Date",
  "MarkAsRead",
  "Publish",
  "ShowAtHome"
];
export const getTableHeader = type => {
  if (type === "corporate") return corporate;
  if (type === "commercial") return commercial;
  if (type === "residential") return residential;
  if (type === "pg") return pg;
  if (type === "hotel") return hotel;
  if (type === "restaurant") return restaurant;
  return [];
};
